import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Lux.",
  description: "Generated by create new one, inc.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full flex justify-between items-center px-8 py-6 border-b border-gray-200 bg-white sticky top-0 z-50" style={{ color: '#171717', fontWeight: 700, WebkitFontSmoothing: 'antialiased' }}>
          <a href="/" className="text-3xl font-bold tracking-tight flex items-center select-none" style={{ textDecoration: 'none' }}>
            <span>Lux</span>
            <span className="text-yellow-500 ml-0.5">.</span>
          </a>
          <nav>
            <ul className="flex gap-8 text-lg font-medium">
              <li><a href="/food" className="nav-underline-link" style={{ color: '#171717', fontWeight: 700, WebkitFontSmoothing: 'antialiased' }}>Food</a></li>
              <li><a href="/interiors" className="nav-underline-link" style={{ color: '#171717', fontWeight: 700, WebkitFontSmoothing: 'antialiased' }}>Interiors</a></li>
              <li><a href="/social-media" className="nav-underline-link" style={{ color: '#171717', fontWeight: 700, WebkitFontSmoothing: 'antialiased' }}>Social Media</a></li>
              <li><a href="/reel" className="nav-underline-link" style={{ color: '#171717', fontWeight: 700, WebkitFontSmoothing: 'antialiased' }}>Reel</a></li>
              <li><a href="/contact" className="nav-underline-link" style={{ color: '#171717', fontWeight: 700, WebkitFontSmoothing: 'antialiased' }}>Contact</a></li>
              <li><a href="https://instagram.com/estudio.ampersand" target="_blank" rel="noopener noreferrer" className="nav-underline-link" style={{ color: '#171717', fontWeight: 700, WebkitFontSmoothing: 'antialiased' }}>Instagram</a></li>
            </ul>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
